# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: QA Brains Demo Automation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install Ruff
        run: uv tool install ruff

      - name: Install Pytest
        run: uv tool install pytest

      - name: Install Allure
        run: uv pip install allure-pytest

      - name: Install dependencies
        run: uv sync

      - name: Install Playwright
        run: uv tool install playwright

      - name: Lint with Ruff
        run: ruff check --fix

      - name: Test with pytest
        run: pytest -s -vv .
